# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tony Phipps, Front-end Developer
email: tonyphipps@gmail.com
description:  > # this means to ignore newlines until "baseurl:"
  Hello. I am Tony Phipps, a Front-end Developer from the United Kingdom.

source: _source

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "http://tonyphipps.co.uk" # the base hostname & protocol for your site

twitter_username: "@neutraltone"
google_analytics: "UA-15367962-2"
disqus_account: tonyphipps

# Social networks usernames
social:
  - title: github
    username: neutraltone
    url: https://github.com/
  - title: codepen
    username: neutraltone
    url: https://codepen.io/
  - title: twitter
    username: neutraltone
    url: https://twitter.com/
  - title: dribbble
    username: neutraltone
    url: https://dribbble.com/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
#paginate: 5
#gems: [jekyll-paginate, jekyll-feed]
gems:
  - jekyll-feed
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md", "assets"]

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

